
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author MARTIAL
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        langue = 0;
        initComponents();
        title = new String[]{"Bienvenue sur le LMS_G8","Welcome on the LMS_G8"};
        setTitle(title[langue]);
        bienvenu = new String[2];
        bienvenu[0] = "Bienvenue ! Laissez s'embellir votre experience dans la gestion de votre bibliothèque";
        bienvenu[1] = "Welcome ! Let your experience about library management be beautified";
        choose = new String[2];
        choose[0]="Choisissez votre langue :";
        choose[1]="Choose your language";
        demarrer = new String[2];
        demarrer[0]="Démmarer ";
        demarrer[1]="Start";
        lblBienvenu.setText(bienvenu[langue]);
        lblChooseLanguage.setText((choose[langue]));
        Demmarer.setText(demarrer[langue]);
        try{
            //Connexion à la bd
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost/lms_g8", "root","");
            statement = connection.createStatement();
            Statement st = connection.createStatement();
            
            //Mettre les clients qui ont dépassés le delai dans la liste noire
             result = statement.executeQuery("SELECT Matricule_emprunteur, SUM((DATE(NOW())-DATE(Date_emprunt)-14)*500) as dette FROM emprunts WHERE DATE(NOW())-DATE(Date_emprunt)>14 AND Date_remise IS NULL AND Matricule_Emprunteur NOT IN (SELECT Matricule_client FROM liste_noire WHERE Date_de_sortie IS NULL) GROUP BY Matricule_Emprunteur");
            while(result.next()){
                statement.executeUpdate("INSERT INTO liste_noire(Matricule_client, Dette) VALUES('"+result.getString("Matricule_Emprunteur")+"', "+result.getInt("dette")+")");
            }
            result = statement.executeQuery("SELECT Matricule_emprunteur, SUM((DATE(NOW())-DATE(Date_emprunt)-14)*500) as dette FROM emprunts WHERE DATE(NOW())-DATE(Date_emprunt)>14 AND Date_remise IS NULL AND Matricule_Emprunteur IN (SELECT Matricule_client FROM liste_noire WHERE Date_de_sortie IS NULL) GROUP BY Matricule_Emprunteur");
            while(result.next()){
                st.executeUpdate("UPDATE liste_noire SET Dette="+result.getInt("dette")+" WHERE Matricule_client='"+result.getString("Matricule_Emprunteur")+"' AND Date_de_sortie IS NULL");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        Demmarer = new javax.swing.JButton();
        lblBienvenu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChooseLanguage = new javax.swing.JLabel();
        comboLangue = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Demmarer.setText("Démmarer ");
        Demmarer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemmarerActionPerformed(evt);
            }
        });
        getContentPane().add(Demmarer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        lblBienvenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBienvenu.setText("Bienvenue ! Laissez s'embellir votre experience dans la gestion de votre bibliothèque");
        getContentPane().add(lblBienvenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 550, 50));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 40)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("G12 LMS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTIAL\\Documents\\NetBeansProjects\\LMS\\src\\main\\java\\images\\uiecc4.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 130, 120));

        lblChooseLanguage.setBackground(new java.awt.Color(255, 255, 255));
        lblChooseLanguage.setText("Choisissez votre langue :");
        getContentPane().add(lblChooseLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        comboLangue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Francais", "English" }));
        comboLangue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLangueItemStateChanged(evt);
            }
        });
        getContentPane().add(comboLangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 100, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTIAL\\Documents\\NetBeansProjects\\LMS\\src\\main\\java\\images\\livres-dans-bibliotheque-ancien-manuel-ouvert-empile-piles-archives-litteraires-pupitre-lecture_1150-9086.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemmarerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemmarerActionPerformed
        // TODO add your handling code here:
        //Définition de la clé de sécurité pour acceder à la partie principale du logiciel
        JPasswordField passwordField = new JPasswordField();
        int confirmButton = JOptionPane.showConfirmDialog(rootPane, passwordField, "Entrer la clé d'accès", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(confirmButton == JOptionPane.OK_OPTION){
            String chaine = new String(passwordField.getPassword());
            if(chaine!=null){
                try{
                    result = statement.executeQuery("SELECT DAY(NOW()) AS param1, HOUR(NOW()) AS param2, MINUTE(NOW()) AS param3");
                    result.next();
                    if(chaine.equals(result.getInt("param2")+"(uiecc"+result.getInt("param1")+"BIBLIO)"+result.getInt("param3"))){
                        JOptionPane.showMessageDialog(rootPane, "Clé validée !! 😏🤓😁");
                        InterfaceDomainesArticles interfaceDomaines = new InterfaceDomainesArticles(this.langue);
                        interfaceDomaines.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Clé invalide 😁❌, veuillez ressayer 🙃");
                    }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            /*String chaine = JOptionPane.showInputDialog("Veuillez entrer la clé d'accès au logiciel pour pouvoir y accéder");
            if(chaine!=null){
                try{
                    result = statement.executeQuery("SELECT DAY(NOW()) AS param1, HOUR(NOW()) AS param2, MINUTE(NOW()) AS param3");
                    result.next();
                    if(chaine.equals(result.getInt("param2")+"(uiecc"+result.getInt("param1")+"BIBLIO)"+result.getInt("param3"))){
                        JOptionPane.showMessageDialog(rootPane, "Clé validée !! 😏🤓😁");
                        InterfaceDomainesArticles interfaceDomaines = new InterfaceDomainesArticles();
                        interfaceDomaines.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Clé invalide 😁❌, veuillez ressayer 🙃");
                    }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }*/
        }
    }//GEN-LAST:event_DemmarerActionPerformed

    private void comboLangueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLangueItemStateChanged
        // TODO add your handling code here:
        langue = comboLangue.getSelectedIndex();
        lblBienvenu.setText(bienvenu[langue]);
        lblChooseLanguage.setText(choose[langue]);
        Demmarer.setText(demarrer[langue]);
        setTitle(title[langue]);
    }//GEN-LAST:event_comboLangueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    private Connection connection;
    private Statement statement;
    private ResultSet result;
    private int langue;
    private String title[];
    private String bienvenu[];
    private String choose[];
    private String demarrer[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demmarer;
    private javax.swing.JComboBox<String> comboLangue;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBienvenu;
    private javax.swing.JLabel lblChooseLanguage;
    // End of variables declaration//GEN-END:variables
}
