/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author MARTIAL
 */
public class InterfaceDomainesArticles extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceClients
     */
    public InterfaceDomainesArticles(int lang) {
        initComponents();
        //Traduction
        langue = lang;
        String title[] = new String[]{"Domaines d'articles","Articles domains"};
        setTitle(title[langue]);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        article = new String[2];
            article[0] = "Articles";
            article[1] = "Items";
            toogleArticles.setText(article[langue]);
        client = new String[2];
            client[0] = "Clients";
            client[1] = "Customers";
            toogleClients.setText(client[langue]);
        pret = new String[2];
            pret[0] = "Prêts";
            pret[1] = "Loans";
            tooglePrets.setText(pret[langue]);
        listeArti = new String[2];
            listeArti[0] = "Liste des articles";
            listeArti[1] = "Item list";
            toogleListeArticles.setText(listeArti[lang]);
        ajouterArti = new String[2];
            ajouterArti[0] = "Ajouter un article";
            ajouterArti[1] = "Add an item";
            toogleAjouterArticle.setText(ajouterArti[lang]);
        recherch = new String[2];
            recherch[0] = "Rechercher";
            recherch[1] = "Search";
            rechercher.setText(recherch[langue]);
        trierPar = new String[2];
            trierPar[0] = "Trier par :";
            trierPar[1] = "Sort by :";
            lblTri.setText(trierPar[langue]);
        informatiqu = new String[2];
            informatiqu[0] = "Informatique";
            informatiqu[1] = "Computer science";
            Informatique.setText(informatiqu[langue]);
        mathematiqu = new String[2];
            mathematiqu[0] = "Mathematiques";
            mathematiqu[1] = "Mathematics";
            Mathematiques.setText(mathematiqu[langue]);
        electroniqu = new String[2];
            electroniqu[0] = "Electronique";
            electroniqu[1] = "Electronic";
            Electronique.setText(electroniqu[langue]);
        scieneFict = new String[2];
            scieneFict[0] = "Science-fiction";
            scieneFict[1] = "Science-fiction";
        litteratur = new String[2];
            litteratur[0] = "Litterature";
            litteratur[1] = "Literature";
            Litterature.setText(litteratur[langue]);
        anthropolo = new String[2];
            anthropolo[0] = "Anthropologie et Culture";
            anthropolo[1] = "Anthropology and Culture";
            Anthropologie.setText(anthropolo[langue]);
        droi = new String[2];
            droi[0] = "Droit";
            droi[1] = "Law";
            Droit.setText(droi[langue]);
        ar = new String[2];
            ar[0] = "Art";
            ar[1] = "Art";
            Art.setText(ar[langue]);
        entrepreneuria = new String[2];
            entrepreneuria[0] = "Entrepreneuriat";
            entrepreneuria[1] = "Entrepreneurship";
            Entrepreneuriat.setText(entrepreneuria[langue]);
        autr = new String[2];
            autr[0] = "Autres";
            autr[1] = "Others";
            Autres.setText(autr[langue]);
    }

    InterfaceDomainesArticles() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        InterfaceDomainesArticles interfaceDomainesArticles1 = new InterfaceDomainesArticles(langue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tooglePrets = new javax.swing.JToggleButton();
        toogleClients = new javax.swing.JToggleButton();
        toogleArticles = new javax.swing.JToggleButton();
        rechercher = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTri = new javax.swing.JLabel();
        Informatique = new javax.swing.JButton();
        Mathematiques = new javax.swing.JButton();
        Electronique = new javax.swing.JButton();
        Anthropologie = new javax.swing.JButton();
        Litterature = new javax.swing.JButton();
        Science_fiction = new javax.swing.JButton();
        Droit = new javax.swing.JButton();
        Art = new javax.swing.JButton();
        Autres = new javax.swing.JButton();
        Entrepreneuriat = new javax.swing.JButton();
        toogleListeArticles = new javax.swing.JToggleButton();
        toogleAjouterArticle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar3 = new javax.swing.JMenuBar();
        Main = new javax.swing.JMenu();
        Edit = new javax.swing.JMenu();
        jMenuClients = new javax.swing.JMenu();
        jMenuArticles = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 243, 175));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 11, -1, -1));

        tooglePrets.setText("Prets");
        tooglePrets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tooglePretsActionPerformed(evt);
            }
        });
        getContentPane().add(tooglePrets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, -1));

        toogleClients.setText("Clients");
        toogleClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleClientsActionPerformed(evt);
            }
        });
        getContentPane().add(toogleClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, -1));

        toogleArticles.setSelected(true);
        toogleArticles.setText("Articles");
        toogleArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleArticlesActionPerformed(evt);
            }
        });
        getContentPane().add(toogleArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        rechercher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 140, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domaine", "Auteur", "Ordre alphabétique", "Maison d'édition" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 77, -1));

        lblTri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTri.setText("Trier par :");
        getContentPane().add(lblTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        Informatique.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Informatique.setText("Informatique");
        Informatique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformatiqueActionPerformed(evt);
            }
        });
        getContentPane().add(Informatique, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        Mathematiques.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mathematiques.setText("Mathematiques");
        Mathematiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathematiquesActionPerformed(evt);
            }
        });
        getContentPane().add(Mathematiques, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        Electronique.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Electronique.setText("Electronique");
        Electronique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectroniqueActionPerformed(evt);
            }
        });
        getContentPane().add(Electronique, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        Anthropologie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Anthropologie.setText("Anthropologie et Culture");
        Anthropologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnthropologieActionPerformed(evt);
            }
        });
        getContentPane().add(Anthropologie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, -1));

        Litterature.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Litterature.setText("Litterature");
        Litterature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LitteratureActionPerformed(evt);
            }
        });
        getContentPane().add(Litterature, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        Science_fiction.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Science_fiction.setText("Science-fiction");
        Science_fiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Science_fictionActionPerformed(evt);
            }
        });
        getContentPane().add(Science_fiction, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        Droit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Droit.setText("Droit");
        Droit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DroitActionPerformed(evt);
            }
        });
        getContentPane().add(Droit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        Art.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Art.setText("Art");
        Art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtActionPerformed(evt);
            }
        });
        getContentPane().add(Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        Autres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Autres.setText("Autres");
        Autres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutresActionPerformed(evt);
            }
        });
        getContentPane().add(Autres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        Entrepreneuriat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Entrepreneuriat.setText("Entrepreuneuriat");
        Entrepreneuriat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrepreneuriatActionPerformed(evt);
            }
        });
        getContentPane().add(Entrepreneuriat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        toogleListeArticles.setText("Liste des articles");
        toogleListeArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleListeArticlesActionPerformed(evt);
            }
        });
        getContentPane().add(toogleListeArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        toogleAjouterArticle.setText("Ajouter un article");
        toogleAjouterArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleAjouterArticleActionPerformed(evt);
            }
        });
        getContentPane().add(toogleAjouterArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTIAL\\Documents\\NetBeansProjects\\LMS\\src\\main\\java\\images\\clientAddin.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 520, 430));

        Main.setText("Main");
        Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMouseClicked(evt);
            }
        });
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });
        jMenuBar3.add(Main);

        Edit.setText("Modifier");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jMenuClients.setText("Clients");
        jMenuClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClientsMouseClicked(evt);
            }
        });
        jMenuClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientsActionPerformed(evt);
            }
        });
        Edit.add(jMenuClients);

        jMenuArticles.setText("Emplacement articles");
        jMenuArticles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuArticlesMouseClicked(evt);
            }
        });
        Edit.add(jMenuArticles);

        jMenuBar3.add(Edit);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toogleArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleArticlesActionPerformed
        // TODO add your handling code here:
        if(toogleArticles.isSelected()){
            toogleClients.setVisible(false);
            tooglePrets.setVisible(false);
        }
    }//GEN-LAST:event_toogleArticlesActionPerformed

    private void toogleAjouterArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleAjouterArticleActionPerformed
        // TODO add your handling code here:
        if(toogleAjouterArticle.isSelected()){
            toogleAjouterArticle.setSelected(true);
            toogleListeArticles.setSelected(false);
            InterfaceAjoutArticles interfaceAjoutArticle = new InterfaceAjoutArticles(langue);
            interfaceAjoutArticle.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_toogleAjouterArticleActionPerformed

    private void toogleListeArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleListeArticlesActionPerformed
        // TODO add your handling code here:
        if(toogleListeArticles.isSelected()){
            toogleListeArticles.setSelected(true);
            toogleAjouterArticle.setSelected(false);
            InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("", langue);
            interfaceListeArticles.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_toogleListeArticlesActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercherActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void toogleClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleClientsActionPerformed
        // TODO add your handling code here:
        if(toogleClients.isSelected()){
            toogleArticles.setVisible(false);
            tooglePrets.setVisible(false);
            InterfaceListeClientsEtudiants interfaceListeDesClients = new InterfaceListeClientsEtudiants("", langue);
            interfaceListeDesClients.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_toogleClientsActionPerformed

    private void tooglePretsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tooglePretsActionPerformed
        // TODO add your handling code here:
        if(tooglePrets.isSelected()){
            toogleClients.setVisible(false);
            toogleArticles.setVisible(false);
            InterfacePrets interfacePrets = new InterfacePrets(langue);
            interfacePrets.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tooglePretsActionPerformed

    private void EntrepreneuriatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrepreneuriatActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Entrepreuneuriat", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntrepreneuriatActionPerformed

    private void InformatiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformatiqueActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Informatique", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InformatiqueActionPerformed

    private void MathematiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathematiquesActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Mathematiques", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MathematiquesActionPerformed

    private void ElectroniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectroniqueActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Electronique", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ElectroniqueActionPerformed

    private void Science_fictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Science_fictionActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Science-fiction", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Science_fictionActionPerformed

    private void LitteratureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LitteratureActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Litterature", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LitteratureActionPerformed

    private void AnthropologieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnthropologieActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Anthropologie et Culture", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnthropologieActionPerformed

    private void DroitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DroitActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Droit", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DroitActionPerformed

    private void ArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Art", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ArtActionPerformed

    private void AutresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutresActionPerformed
        // TODO add your handling code here:
        InterfaceListeArticles interfaceListeArticles = new InterfaceListeArticles("Autre", langue);
        interfaceListeArticles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AutresActionPerformed

    private void MainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseClicked
        // TODO add your handling code here:
        InterfaceDomainesArticles listeDomaines = new InterfaceDomainesArticles(langue);
        listeDomaines.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMouseClicked

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainActionPerformed

    private void jMenuClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientsMouseClicked
        // TODO add your handling code here:
        InterfaceListeClientsModifiable clientsModifiables = new InterfaceListeClientsModifiable(langue);
        clientsModifiables.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuClientsMouseClicked

    private void jMenuClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuClientsActionPerformed

    private void jMenuArticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuArticlesMouseClicked
        // TODO add your handling code here:
        InterfaceListeArticlesModifiable listeArticlesModifiables = new InterfaceListeArticlesModifiable("", langue);
        listeArticlesModifiables.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuArticlesMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDomainesArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDomainesArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDomainesArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDomainesArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDomainesArticles(langue).setVisible(true);
            }
        });
    }

    static int langue;
    private String article[];
    private String client[];
    private String pret[];
    private String listeArti[];
    private String ajouterArti[];
    private String recherch[];
    private String trierPar[];
    private String informatiqu[];
    private String mathematiqu[];
    private String electroniqu[];
    private String scieneFict[];
    private String litteratur[];
    private String anthropolo[];
    private String droi[];
    private String ar[];
    private String entrepreneuria[];
    private String autr[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anthropologie;
    private javax.swing.JButton Art;
    private javax.swing.JButton Autres;
    private javax.swing.JButton Droit;
    private javax.swing.JMenu Edit;
    private javax.swing.JButton Electronique;
    private javax.swing.JButton Entrepreneuriat;
    private javax.swing.JButton Informatique;
    private javax.swing.JButton Litterature;
    private javax.swing.JMenu Main;
    private javax.swing.JButton Mathematiques;
    private javax.swing.JButton Science_fiction;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuArticles;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuClients;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTri;
    private javax.swing.JTextField rechercher;
    private javax.swing.JToggleButton toogleAjouterArticle;
    private javax.swing.JToggleButton toogleArticles;
    private javax.swing.JToggleButton toogleClients;
    private javax.swing.JToggleButton toogleListeArticles;
    private javax.swing.JToggleButton tooglePrets;
    // End of variables declaration//GEN-END:variables
}
